# Generated by Django 4.2.4 on 2023-08-28 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagemodel",
            options={"verbose_name_plural": "2. 메세지 내역"},
        ),
        migrations.AlterModelOptions(
            name="roommodel",
            options={"verbose_name_plural": "1. 채팅방 목록"},
        ),
    ]
