# Generated by Django 4.2.4 on 2023-11-20 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_rename_tel_storemodel_phone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_messagemodel_options_alter_roommodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roommodel",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.storemodel",
                verbose_name="스토어",
            ),
        ),
        migrations.AlterField(
            model_name="roommodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저",
            ),
        ),
    ]
